export const COMMERCIAL_PERMISSIONS = {
  COMMERCIAL_DATA_ACCESS: 'commercial_data:access',
  QUOTATIONS_VIEW: 'quotations:view',
  QUOTATIONS_MANAGE: 'quotations:manage',
  CONTRACTS_VIEW: 'contracts:view',
  CONTRACTS_MANAGE: 'contracts:manage',
  PURCHASE_ORDERS_VIEW: 'purchase_orders:view',
  PURCHASE_ORDERS_MANAGE: 'purchase_orders:manage',
  INVOICES_VIEW: 'invoices:view',
  INVOICES_MANAGE: 'invoices:manage',
  MISSIONS_VIEW: 'missions:view',
  MISSION_COMMERCIAL_DATA_VIEW: 'mission_commercial_data:view',
  MISSION_COMMERCIAL_DATA_UPDATE: 'mission_commercial_data:update',
  PLACEMENT_COMMERCIAL_ELIGIBILITY_VIEW: 'placement_commercial_eligibility:view',
} as const;
