process.env.ACCESS_TOKEN_TTL_SECONDS ??= '300';
process.env.API_CORS_ORIGIN ??= 'http://127.0.0.1:5173';
process.env.API_HOST ??= '127.0.0.1';
process.env.API_PORT ??= '3000';
process.env.AUTH_ACCESS_TOKEN_SECRET ??= 'test_access_token_secret_32_characters_minimum';
process.env.AUTH_COOKIE_SECURE ??= 'false';
process.env.AUTH_REFRESH_TOKEN_PEPPER ??= 'test_refresh_token_pepper_32_characters_minimum';
process.env.DATABASE_URL ??=
  'postgresql://hire_me:hire_me_dev_password@127.0.0.1:5432/hire_me_dev?schema=public';
process.env.NODE_ENV ??= 'test';
process.env.PRIVATE_UPLOAD_STORAGE_ROOT ??= '.tmp-runtime/test-private-uploads';
process.env.PUBLIC_APPLICATION_JSON_LIMIT ??= '6mb';
process.env.REFRESH_TOKEN_TTL_SECONDS ??= '604800';
